// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SupervisorDashboard.Data;

#nullable disable

namespace SupervisorDashboard.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260629104222_AddMiktar")]
    partial class AddMiktar
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("SupervisorDashboard.Models.FactoryLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AkuTipi")
                        .HasColumnType("TEXT");

                    b.Property<string>("EtiketTipi")
                        .HasColumnType("TEXT");

                    b.Property<string>("ForkliftId")
                        .HasColumnType("TEXT");

                    b.Property<string>("HedefBant")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Miktar")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RafKonumu")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FactoryLogs");
                });

            modelBuilder.Entity("SupervisorDashboard.Models.MamulDepoIslem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("HedefBant")
                        .HasColumnType("TEXT")
                        .HasColumnName("hedef_bant");

                    b.Property<string>("IslemDurumu")
                        .HasColumnType("TEXT")
                        .HasColumnName("islem_durumu");

                    b.Property<DateTime>("IslemZamani")
                        .HasColumnType("TEXT")
                        .HasColumnName("islem_zamani");

                    b.Property<string>("LokasyonAdi")
                        .HasColumnType("TEXT")
                        .HasColumnName("lokasyon_adi");

                    b.Property<string>("LokasyonNo")
                        .HasColumnType("TEXT")
                        .HasColumnName("lokasyon_no");

                    b.Property<string>("LotGrupNo")
                        .HasColumnType("TEXT")
                        .HasColumnName("lot_grup_no");

                    b.Property<string>("MalzemeAciklamasi")
                        .HasColumnType("TEXT")
                        .HasColumnName("malzeme_aciklamasi");

                    b.Property<int>("Miktar")
                        .HasColumnType("INTEGER")
                        .HasColumnName("miktar");

                    b.Property<string>("StokKodu")
                        .HasColumnType("TEXT")
                        .HasColumnName("stok_kodu");

                    b.Property<string>("UlkeSeriNo")
                        .HasColumnType("TEXT")
                        .HasColumnName("ulke_seri_no");

                    b.HasKey("Id");

                    b.ToTable("mamul_depo_islemleri");
                });
#pragma warning restore 612, 618
        }
    }
}
